[eclipse/xtext-core#759] Use new EMF update site locations
xtext/xtext-p2-orbit pull request #21
Opened 2019-04-05 11:55 UTC by kthoms

Signed-off-by: Karsten Thoms <karsten.thoms@itemis.de>

2019-04-05 11:56 UTC, cdietrich approved these changes

2019-04-05 12:44 UTC, cdietrich requested changes
bad changes

2019-04-05 12:45 UTC, cdietrich commented on composite/releases/compositeArtifacts.xml
>      <child location='http://download.eclipse.org/modeling/emf/emf/updates/2.10.x/'/>
this one should be changed, not mwe

2019-04-05 12:45 UTC, cdietrich commented on composite/releases/compositeContent.xml
>      <child location='http://download.eclipse.org/modeling/emf/emf/updates/2.10.x/'/>
this one should be changed. not mwe

2019-04-05 12:45 UTC, cdietrich commented on composite/releases/compositeContent.xml
> +    <child location='http://download.eclipse.org/modeling/emf/emf/builds/release/'/>
this is mwe,not emf

2019-04-05 12:45 UTC, cdietrich commented on composite/releases/compositeArtifacts.xml
> +    <child location='http://download.eclipse.org/modeling/emf/emf/builds/release/'/>
this is mwe,not emf

2019-04-05 14:29 UTC, kthoms commented on composite/releases/compositeArtifacts.xml
>      <child location='http://download.eclipse.org/modeling/emf/emf/updates/2.10.x/'/>
Updated.

2019-05-07 06:54 UTC, cdietrich approved these changes

2019-05-07 06:54 UTC, merged